# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-08-02 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arya_lib', '0002_auto_20160802_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login_list',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
