# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-08-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arya_lib', '0003_auto_20160802_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('bookname', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=30)),
                ('book_id', models.IntegerField(default=0)),
                ('issue_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='user_login_list',
        ),
    ]
