# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-08-23 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arya_lib', '0005_book_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_list',
            name='book_id',
            field=models.IntegerField(),
        ),
    ]
